# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - main: ./go-hello
    binary: go-hello
    goos:
      - linux
      - windows
    goarch:
      - arm
      - ppc64le
      - amd64
dockers:
  - id: 1
    goos: linux
    goarch: amd64
    image_templates:
      - "adysh97/go-hello:latest"
    skip_push: true
    build_flag_templates:
      - "--platform=amd64"
