name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: GoReleaser Action
      # You may pin to the exact commit or the version.
      # uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef
      uses: goreleaser/goreleaser-action@v3.0.0
      with:
        # GoReleaser Distribution (goreleaser or goreleaser-pro)
        distribution: # optional, default is goreleaser
        # GoReleaser version
        version: # optional, default is latest
        # Arguments to pass to GoReleaser
        args: release --snapshot --rm-dist 
        # Working directory (below repository root)
        workdir: # optional, default is .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
